export const GENDER = [
  { name: "مرد", value: "male" },
  { name: "زن", value: "female" },
];

export const FLEET_FREE_TYPE = [
  { title: "آزاد", id: "false" },
  { title: "همه", id: "true" },
];
export const SENDER_RECEIVER = [
  { title: "فرستنده", id: "sender" },
  { title: "گیرنده", id: "receiver" },
];
export const RATE_TYPE = {
  driver: "راننده",
  customer: "صاحب‌بار",
  company: "شرکت حمل",
};

export const PAGE_TITLES = {
  "/desktop": "میزکار",
  "/waybill/newWaybill": "ثبت بارنامه جدید",
  "/waybill/NewDraft": "ثبت حواله جدید",
  "/waybill/Draft": "لیست حواله‌ها",
  "/waybill": "لیست بارنامه‌ها",
  "/contract": "لیست قراردادها",
  "/prices": "قیمت‌ها",
  "/contract/new": "ثبت قرارداد جدید",
  "/project/new": "ثبت پروژه جدید",
  "/project": "لیست پروژه‌ها",
  "/request/tune": "لیست آهنگ پروژه‌ها",
  "/request/new-tune": "ثبت آهنگ پروژه",
  "/request/new": "ثبت درخواست حمل",
  "/request": "لیست درخواست حمل",
  "/project/shipping-plan-new": "برنامه‌ریزی پروژه",
  "/shippingCompany": "لیست شرکت حمل و نقل",
  "/fleet": "لیست ناوگان",
  "/fleet/free": "لیست ناوگان آزاد",
  "/fleet/new": "ثبت ناوگان پروژه",
  "/beneficiary": "ذی‌نفعان",
  "/request/fleet-allocation": "تخصیص ناوگان",
  "/product": "لیست محصولات",
  "/product/group": "دسته‌بندی",
  "/product/unit": "واحد شمارشی",
  "/customer": "لیست صاحبان‌بار",
  "/customer/new": "ثبت صاحب‌‌بار جدید",
  "/driver": "لیست رانندگان",
  "/driver/new": "ثبت راننده جدید",
  "/person": "لیست فرستندگان و گیرندگان",
  "/person/new": "ثبت فرستنده و گیرنده جدید",
  "/vehicle": "لیست خودرو‌ها",
  "/vehicle/category": "نوع کامیون",
  "/vehicle/brand": "برند",
  "/vehicle/type": "نوع بارگیر",
  "/vehicle/model": "مدل خودرو",
  "/vehicle/refueling": "سوخت‌گیری",
  "/user": "لیست کاربران",
  "/super-app": "مدیریت سوپر اپ",
  "/role": "لیست نقش‌ها",
  "/event": "رویداد‌ها",
  "/settings": "تنظیمات",
  "/request/salon": "لیست سالن بار",
  "/fleet/group": "گروه ناوگان",
  "/super-app/section/item": "آیتم‌ها",
  "/super-app/section": "بخش‌‌ها",
};
